import Link from 'next/link'
import {
  fetchCliCommands,
  groupCliCommands,
  type CliCommandsDocument,
} from '@/lib/docs'
import { copy } from '@/lib/copy'
import { CodeBlock } from '../../_components/DocSchema'

/*
 * The CLI reference (MOTIR-4046, GENERATED by MOTIR-4395) — rendered from
 * motir-core's PUBLISHED command catalogue (`/api/docs/cli-commands.json`),
 * fetched fresh at request time, exactly as `/docs/api` renders the OpenAPI
 * document and `/docs/mcp/tools` renders the tool catalogue.
 *
 * ⚠️ WHAT WAS HERE, AND WHY IT COULD NOT BE FIXED IN THIS REPOSITORY ALONE.
 * The page was five sentences of positioning: no install line, no
 * authentication, no command list, no flags, no examples. Three `<code>`
 * elements and zero `<pre>` blocks. The obvious fix — generate it from the
 * published catalogue — asserted a door that does not exist: `@motir/cli`
 * publishes `exports: { "./package.json": … }` and nothing else, so
 * `COMMAND_CATALOG` sits inside `dist/index.js` reachable by no import.
 * MOTIR-4390 opened the door as a served artifact; this consumes it.
 *
 * ⚠️ NOTHING ABOUT THE COMMAND SET IS WRITTEN DOWN HERE. No command list, no
 * flag reference, no default server. They arrive over the wire and live in this
 * file for the length of one render — the same property `/docs/mcp/tools`
 * keeps, and `tests/docs/cli.test.tsx` asserts it: the production server's URL
 * may not appear in this source as a literal of its own, because the catalogue
 * carries it and a second copy could disagree with the binary a reader
 * installed. (That guard caught this very comment while it was being written,
 * which is the guard earning its place — the URL is not spelled here either.)
 * What IS typed is the four-line first-run procedure, which is prose about the
 * order a reader types things in; the test carries the ceiling and the reason.
 *
 * ⚠️ THE POSITIONING PARAGRAPH STAYS, as the card asks. It is good writing; it
 * simply is not documentation. It introduces the reference rather than standing
 * in for one.
 *
 * ⚠️ NO FALLBACK, DELIBERATELY. A committed command list is stale exactly when
 * it is displayed and invisible to every guard, since a guard runs on the path
 * where the fetch works — which is the defect MOTIR-4180 removed from this
 * repository. Unreachable ⇒ the page SAYS SO, and the introduction and the
 * hand-offs still render, so a reader is never stranded.
 *
 * ⚠️ MERGE ORDER. `/api/docs/cli-commands.json` ships in MOTIR-4390 and does
 * not exist on the deployed app until that merges and deploys. Until then this
 * page renders the unreachable state, which is the honest answer and not a
 * regression: the alternative is a committed list, which is the thing being
 * removed. motir-core merges first.
 */
export const dynamic = 'force-dynamic'

function Intro() {
  return (
    <p className="mt-4 max-w-[68ch] text-[15px] leading-relaxed text-(--el-text)">
      The Motir CLI talks to the same MCP server the hosted agents use. It
      automates the planning-and-execution loop over a workspace-scoped token: a
      run claims the next ready work item, fetches the server-generated prompt,
      and dispatches an agent in a sandbox to execute it. The card is the system
      of record; the CLI is the driver.
    </p>
  )
}

function Command({
  command,
}: {
  command: CliCommandsDocument['commands'][number]
}) {
  return (
    <li className="py-4">
      <code className="font-(family-name:--font-mono) text-[13.5px] font-semibold text-(--el-text)">
        {command.invocation}
      </code>
      <p className="mt-1 max-w-[68ch] text-[13px] leading-relaxed text-(--el-text-secondary)">
        {command.description}
      </p>
      {command.options.length > 0 ? (
        <dl className="mt-2 grid grid-cols-[minmax(0,14rem)_1fr] gap-x-4 gap-y-1.5">
          {command.options.map((option) => (
            <div key={option.flags} className="contents">
              <dt className="font-(family-name:--font-mono) text-[12.5px] text-(--el-text)">
                {option.flags}
              </dt>
              <dd className="m-0 min-w-0 text-[12.5px] leading-relaxed text-(--el-text-secondary)">
                {option.description}
              </dd>
            </div>
          ))}
        </dl>
      ) : null}
    </li>
  )
}

export default async function CliPage() {
  let catalogue: CliCommandsDocument
  try {
    catalogue = await fetchCliCommands()
  } catch {
    return (
      <>
        <h1 className="font-(family-name:--font-serif) text-[30px] leading-[1.2] font-bold tracking-[-0.01em] text-(--el-text)">
          {copy.docs.cli}
        </h1>
        <Intro />
        <p className="mt-6 max-w-[68ch] text-[14px] leading-relaxed text-(--el-text-secondary)">
          The command reference is temporarily unreachable. It is generated from
          the catalogue the CLI itself declares and is never copied here, so
          there is nothing to show you in the meantime —{' '}
          <code className="rounded-(--radius-kbd) bg-(--el-muted) px-1.5 py-0.5 font-(family-name:--font-mono) text-[13px]">
            motir help
          </code>{' '}
          prints the same table from the binary you have installed.
        </p>
      </>
    )
  }

  const groups = groupCliCommands(catalogue)

  return (
    <>
      <h1 className="font-(family-name:--font-serif) text-[30px] leading-[1.2] font-bold tracking-[-0.01em] text-(--el-text)">
        {copy.docs.cli}
      </h1>
      <p className="mt-2 text-[13px] text-(--el-text-secondary)">
        {catalogue.packageName} · version {catalogue.packageVersion} ·{' '}
        {catalogue.commandCount} commands
      </p>
      <Intro />

      <h2 className="mt-9 font-(family-name:--font-serif) text-[20px] font-semibold text-(--el-text)">
        Install
      </h2>
      <p className="mt-2 max-w-[68ch] text-[14px] leading-relaxed text-(--el-text-secondary)">
        Node {catalogue.nodeRequirement}. Install it globally, or run it once
        without installing.
      </p>
      <div className="mt-3">
        <CodeBlock
          caption="install"
          code={`${catalogue.installCommand}\n\n# or, without installing:\nnpx ${catalogue.packageName} --help`}
        />
      </div>

      <h2 className="mt-9 font-(family-name:--font-serif) text-[20px] font-semibold text-(--el-text)">
        Authenticate
      </h2>
      <p className="mt-2 max-w-[68ch] text-[14px] leading-relaxed text-(--el-text-secondary)">
        The device flow is the shortest path: it shows a code, opens Motir, and
        waits for you to approve it. If you already hold a personal access
        token, hand it over directly instead. Either way the CLI talks to{' '}
        <code className="rounded-(--radius-kbd) bg-(--el-muted) px-1.5 py-0.5 font-(family-name:--font-mono) text-[13px]">
          {catalogue.defaultServer}
        </code>{' '}
        unless you point it somewhere else.
      </p>
      <div className="mt-3">
        <CodeBlock
          caption="authenticate"
          code={`motir login\n\n# or with a token you already hold:\nmotir auth login --server ${catalogue.defaultServer} --token <pat>\n\n# or from the environment:\nexport MOTIR_SERVER=${catalogue.defaultServer}\nexport MOTIR_TOKEN=<pat>`}
        />
      </div>
      <p className="mt-1 max-w-[68ch] text-[13px] leading-relaxed text-(--el-text-secondary)">
        Then bind a folder to a project, and check the setup before the first
        run.
      </p>
      <div className="mt-3">
        <CodeBlock
          caption="link and check"
          code={`motir link --project ACME\nmotir doctor`}
        />
      </div>

      <h2 className="mt-9 font-(family-name:--font-serif) text-[20px] font-semibold text-(--el-text)">
        Commands
      </h2>
      <p className="mt-2 max-w-[68ch] text-[14px] leading-relaxed text-(--el-text-secondary)">
        Every command the CLI registers, in the order{' '}
        <code className="rounded-(--radius-kbd) bg-(--el-muted) px-1.5 py-0.5 font-(family-name:--font-mono) text-[13px]">
          motir help
        </code>{' '}
        prints them, generated from the catalogue the binary itself declares —
        so this list cannot fall behind a release. It describes{' '}
        {catalogue.packageName}@{catalogue.packageVersion}.
      </p>

      {groups.map((group) => (
        <section key={group.heading} className="mt-7">
          <h3 className="text-[11px] font-semibold tracking-wide text-(--el-text-secondary) uppercase">
            {group.heading}
          </h3>
          <ul className="mt-2 flex flex-col divide-y divide-(--el-border) border-y border-(--el-border)">
            {group.commands.map((command) => (
              <Command key={command.path} command={command} />
            ))}
          </ul>
        </section>
      ))}

      <h2 className="mt-9 font-(family-name:--font-serif) text-[20px] font-semibold text-(--el-text)">
        Where a run executes
      </h2>
      <p className="mt-2 max-w-[68ch] text-[14px] leading-relaxed text-(--el-text-secondary)">
        A dispatched agent runs inside a container with your checkouts and your
        own agent credential — what it provides, what its token refuses, and the
        failures a first run hits are on the{' '}
        <Link
          href="/docs/sandbox"
          className="text-(--el-accent-on-surface) underline underline-offset-2"
        >
          {copy.docs.sandbox}
        </Link>{' '}
        page rather than restated here. Wiring an agent to Motir without the CLI
        is{' '}
        <Link
          href="/docs/mcp"
          className="text-(--el-accent-on-surface) underline underline-offset-2"
        >
          {copy.docs.mcp}
        </Link>
        .
      </p>
    </>
  )
}
