import Link from 'next/link'
import {
  fetchCliCommands,
  groupCliCommands,
  type CliCommandsDocument,
} from '@/lib/docs'
import { copy } from '@/lib/copy'
import { CodeBlock } from '../../_components/DocSchema'

/*
 * The CLI reference (MOTIR-4046, GENERATED by MOTIR-4395) — rendered from
 * motir-core's PUBLISHED command catalogue (`/api/docs/cli-commands.json`),
 * fetched fresh at request time, exactly as `/docs/api` renders the OpenAPI
 * document and `/docs/mcp/tools` renders the tool catalogue.
 *
 * ⚠️ WHAT WAS HERE, AND WHY IT COULD NOT BE FIXED IN THIS REPOSITORY ALONE.
 * The page was five sentences of positioning: no install line, no
 * authentication, no command list, no flags, no examples. Three `<code>`
 * elements and zero `<pre>` blocks. The obvious fix — generate it from the
 * published catalogue — asserted a door that does not exist: `@motir/cli`
 * publishes `exports: { "./package.json": … }` and nothing else, so
 * `COMMAND_CATALOG` sits inside `dist/index.js` reachable by no import.
 * MOTIR-4390 opened the door as a served artifact; this consumes it.
 *
 * ⚠️ NOTHING ABOUT THE COMMAND SET IS WRITTEN DOWN HERE. No command list, no
 * flag reference, no default server. They arrive over the wire and live in this
 * file for the length of one render — the same property `/docs/mcp/tools`
 * keeps, and `tests/docs/cli.test.tsx` asserts it: the production server's URL
 * may not appear in this source as a literal of its own, because the catalogue
 * carries it and a second copy could disagree with the binary a reader
 * installed. (That guard caught this very comment while it was being written,
 * which is the guard earning its place — the URL is not spelled here either.)
 * What IS typed is the four-line first-run procedure, which is prose about the
 * order a reader types things in; the test carries the ceiling and the reason.
 *
 * ⚠️ THE POSITIONING PARAGRAPH STAYS, as the card asks. It is good writing; it
 * simply is not documentation. It introduces the reference rather than standing
 * in for one.
 *
 * ⚠️ NO FALLBACK, DELIBERATELY. A committed command list is stale exactly when
 * it is displayed and invisible to every guard, since a guard runs on the path
 * where the fetch works — which is the defect MOTIR-4180 removed from this
 * repository. Unreachable ⇒ the page SAYS SO, and the introduction and the
 * hand-offs still render, so a reader is never stranded.
 *
 * ⚠️ MERGE ORDER. `/api/docs/cli-commands.json` ships in MOTIR-4390 and does
 * not exist on the deployed app until that merges and deploys. Until then this
 * page renders the unreachable state, which is the honest answer and not a
 * regression: the alternative is a committed list, which is the thing being
 * removed. motir-core merges first.
 *
 * ── ⚠️ *Where Motir keeps things* IS BACK (MOTIR-4429) ──────────────────────
 * The deleted page carried a `files` section naming the credential store and
 * the project link with the path of each; the restore dropped it, and
 * MOTIR-4397's parity ledger measured that. It is AUTHORED prose, deliberately:
 * the published catalogue carries commands, flags and the default server, and
 * no file path at all — so there is nothing to derive it from, and `lib/docs.ts`'s
 * own carve-out is what allows it. Read from `motir-core`
 * `packages/cli/src/help.ts`'s FILES topic on `origin/main`, which is the same
 * text `motir help files` prints.
 *
 * ⚠️ AND THE CARD SAID *THREE* WHERE THE DELETED PAGE NAMED *TWO* — the card is
 * right and its history is not. The deleted `files` section listed the
 * credential store and the project link; the session exclude list is a THIRD
 * file the CLI grew afterwards, and `motir help files` names all three today.
 * So this restores the shipped set rather than the deleted one, which is the
 * only version that is true. Recorded because a later reader diffing this
 * against `95a2d4468^` will find one row that was never there.
 */
export const dynamic = 'force-dynamic'

export const metadata = {
  title: copy.docs.metaTitleCli,
  description: copy.docs.metaDescriptionCli,
}

/** motir-core's own CLI reference — the authority beyond this page. */
const CLI_REFERENCE_URL =
  'https://github.com/moooon-B-V/motir-core/blob/main/docs/cli.md'

function Intro() {
  return (
    <p className="mt-4 max-w-[68ch] text-[15px] leading-relaxed text-(--el-text)">
      The Motir CLI talks to the same MCP server the hosted agents use. It
      automates the planning-and-execution loop over a workspace-scoped token: a
      run claims the next ready work item, fetches the server-generated prompt,
      and dispatches an agent in a sandbox to execute it. The card is the system
      of record; the CLI is the driver.
    </p>
  )
}

function Command({
  command,
}: {
  command: CliCommandsDocument['commands'][number]
}) {
  return (
    <li className="py-4">
      <code className="font-(family-name:--font-mono) text-[13.5px] font-semibold text-(--el-text)">
        {command.invocation}
      </code>
      <p className="mt-1 max-w-[68ch] text-[13px] leading-relaxed text-(--el-text-secondary)">
        {command.description}
      </p>
      {command.options.length > 0 ? (
        <dl className="mt-2 grid grid-cols-[minmax(0,14rem)_1fr] gap-x-4 gap-y-1.5">
          {command.options.map((option) => (
            <div key={option.flags} className="contents">
              <dt className="font-(family-name:--font-mono) text-[12.5px] text-(--el-text)">
                {option.flags}
              </dt>
              <dd className="m-0 min-w-0 text-[12.5px] leading-relaxed text-(--el-text-secondary)">
                {option.description}
              </dd>
            </div>
          ))}
        </dl>
      ) : null}
    </li>
  )
}

export default async function CliPage() {
  let catalogue: CliCommandsDocument
  try {
    catalogue = await fetchCliCommands()
  } catch {
    return (
      <>
        <h1 className="font-(family-name:--font-serif) text-[30px] leading-[1.2] font-bold tracking-[-0.01em] text-(--el-text)">
          {copy.docs.cli}
        </h1>
        <Intro />
        <p className="mt-6 max-w-[68ch] text-[14px] leading-relaxed text-(--el-text-secondary)">
          The command reference is temporarily unreachable. It is generated from
          the catalogue the CLI itself declares and is never copied here, so
          there is nothing to show you in the meantime —{' '}
          <code className="rounded-(--radius-kbd) bg-(--el-muted) px-1.5 py-0.5 font-(family-name:--font-mono) text-[13px]">
            motir help
          </code>{' '}
          prints the same table from the binary you have installed.
        </p>
      </>
    )
  }

  const groups = groupCliCommands(catalogue)

  return (
    <>
      <h1 className="font-(family-name:--font-serif) text-[30px] leading-[1.2] font-bold tracking-[-0.01em] text-(--el-text)">
        {copy.docs.cli}
      </h1>
      <p className="mt-2 text-[13px] text-(--el-text-secondary)">
        {catalogue.packageName} · version {catalogue.packageVersion} ·{' '}
        {catalogue.commandCount} commands
      </p>
      <Intro />

      <h2 className="mt-9 font-(family-name:--font-serif) text-[20px] font-semibold text-(--el-text)">
        Install
      </h2>
      <p className="mt-2 max-w-[68ch] text-[14px] leading-relaxed text-(--el-text-secondary)">
        Node {catalogue.nodeRequirement}. Install it globally, or run it once
        without installing.
      </p>
      <div className="mt-3">
        <CodeBlock
          caption="install"
          code={`${catalogue.installCommand}\n\n# or, without installing:\nnpx ${catalogue.packageName} --help`}
        />
      </div>

      <h2 className="mt-9 font-(family-name:--font-serif) text-[20px] font-semibold text-(--el-text)">
        Authenticate
      </h2>
      <p className="mt-2 max-w-[68ch] text-[14px] leading-relaxed text-(--el-text-secondary)">
        The device flow is the shortest path: it shows a code, opens Motir, and
        waits for you to approve it. If you already hold a personal access
        token, hand it over directly instead. Either way the CLI talks to{' '}
        <code className="rounded-(--radius-kbd) bg-(--el-muted) px-1.5 py-0.5 font-(family-name:--font-mono) text-[13px]">
          {catalogue.defaultServer}
        </code>{' '}
        unless you point it somewhere else.
      </p>
      <div className="mt-3">
        <CodeBlock
          caption="authenticate"
          code={`motir login\n\n# or with a token you already hold:\nmotir auth login --server ${catalogue.defaultServer} --token <pat>\n\n# or from the environment:\nexport MOTIR_SERVER=${catalogue.defaultServer}\nexport MOTIR_TOKEN=<pat>`}
        />
      </div>
      <p className="mt-1 max-w-[68ch] text-[13px] leading-relaxed text-(--el-text-secondary)">
        Then bind a folder to a project, and check the setup before the first
        run.
      </p>
      <div className="mt-3">
        <CodeBlock
          caption="link and check"
          code={`motir link --project ACME\nmotir doctor`}
        />
      </div>

      <h2 className="mt-9 font-(family-name:--font-serif) text-[20px] font-semibold text-(--el-text)">
        Commands
      </h2>
      <p className="mt-2 max-w-[68ch] text-[14px] leading-relaxed text-(--el-text-secondary)">
        Every command the CLI registers, in the order{' '}
        <code className="rounded-(--radius-kbd) bg-(--el-muted) px-1.5 py-0.5 font-(family-name:--font-mono) text-[13px]">
          motir help
        </code>{' '}
        prints them, generated from the catalogue the binary itself declares —
        so this list cannot fall behind a release. It describes{' '}
        {catalogue.packageName}@{catalogue.packageVersion}.
      </p>

      {groups.map((group) => (
        <section key={group.heading} className="mt-7">
          <h3 className="text-[11px] font-semibold tracking-wide text-(--el-text-secondary) uppercase">
            {group.heading}
          </h3>
          <ul className="mt-2 flex flex-col divide-y divide-(--el-border) border-y border-(--el-border)">
            {group.commands.map((command) => (
              <Command key={command.path} command={command} />
            ))}
          </ul>
        </section>
      ))}

      <h2 className="mt-9 font-(family-name:--font-serif) text-[20px] font-semibold text-(--el-text)">
        Where Motir keeps things
      </h2>
      <p className="mt-2 max-w-[68ch] text-[14px] leading-relaxed text-(--el-text-secondary)">
        Three files, and only one of them holds a secret — it is not the one
        that lives in your repository. Every path below can be relocated;{' '}
        <code className="rounded-(--radius-kbd) bg-(--el-muted) px-1.5 py-0.5 font-(family-name:--font-mono) text-[13px]">
          motir help files
        </code>{' '}
        prints them from the binary you actually installed, with the variable
        that moves each one.
      </p>
      <dl className="mt-3 max-w-[68ch] space-y-4 text-[14px] leading-relaxed text-(--el-text-secondary)">
        <div>
          <dt className="font-(family-name:--font-mono) text-[13px] break-all text-(--el-text)">
            ~/.config/motir/config.json{' '}
            <span className="font-(family-name:--font-sans) text-[12px] font-semibold text-(--el-text-strong)">
              — secret, never commit
            </span>
          </dt>
          <dd className="m-0 mt-1">
            The credential store: the only file a personal access token is ever
            written to,{' '}
            <code className="font-(family-name:--font-mono) text-[13px]">
              chmod 600
            </code>{' '}
            inside a{' '}
            <code className="font-(family-name:--font-mono) text-[13px]">
              0700
            </code>{' '}
            directory, keyed by server URL so one machine can hold tokens for
            several Motir servers. It also holds the agent command you
            configured. Relocate it with{' '}
            <code className="font-(family-name:--font-mono) text-[13px]">
              MOTIR_CONFIG_HOME
            </code>{' '}
            or{' '}
            <code className="font-(family-name:--font-mono) text-[13px]">
              XDG_CONFIG_HOME
            </code>
            .
          </dd>
        </div>
        <div>
          <dt className="font-(family-name:--font-mono) text-[13px] break-all text-(--el-text)">
            .motir.json{' '}
            <span className="font-(family-name:--font-sans) text-[12px] font-semibold text-(--el-text-strong)">
              — no secret, safe to commit
            </span>
          </dt>
          <dd className="m-0 mt-1">
            The project link at your workspace root: the server, workspace and
            project this folder is bound to, plus an optional repository
            override map. It carries no credential, so it belongs in version
            control. Every command resolves it by walking UPWARD from the
            current directory, so any command works from inside any checkout
            under the root.
          </dd>
        </div>
        <div>
          <dt className="font-(family-name:--font-mono) text-[13px] break-all text-(--el-text)">
            ~/.local/state/motir/session-excludes.json{' '}
            <span className="font-(family-name:--font-sans) text-[12px] font-semibold text-(--el-text-strong)">
              — no secret
            </span>
          </dt>
          <dd className="m-0 mt-1">
            The session exclude list: the work items whose dispatch FAILED, so
            the next run moves past them instead of re-picking the same failure.
            State rather than a credential, which is why it does not sit beside
            the token — the sandbox mounts the config directory read-only, and a
            run must never die because it could not write this file. If it is
            unwritable Motir warns once and continues. Relocate it with{' '}
            <code className="font-(family-name:--font-mono) text-[13px]">
              MOTIR_STATE_HOME
            </code>
            .
          </dd>
        </div>
      </dl>

      <h2 className="mt-9 font-(family-name:--font-serif) text-[20px] font-semibold text-(--el-text)">
        Where a run executes
      </h2>
      <p className="mt-2 max-w-[68ch] text-[14px] leading-relaxed text-(--el-text-secondary)">
        A dispatched agent runs inside a container with your checkouts and your
        own agent credential — what it provides, what its token refuses, and the
        failures a first run hits are on the{' '}
        <Link
          href="/docs/sandbox"
          className="text-(--el-accent-on-surface) underline underline-offset-2"
        >
          {copy.docs.sandbox}
        </Link>{' '}
        page rather than restated here. Wiring an agent to Motir without the CLI
        is{' '}
        <Link
          href="/docs/mcp"
          className="text-(--el-accent-on-surface) underline underline-offset-2"
        >
          {copy.docs.mcp}
        </Link>
        , and driving the same work loop over HTTP is the{' '}
        <Link
          href="/docs/api"
          className="text-(--el-accent-on-surface) underline underline-offset-2"
        >
          {copy.docs.api}
        </Link>
        . The full command reference — the three run shapes, session branches,
        the failure policy and troubleshooting — is{' '}
        <a
          href={CLI_REFERENCE_URL}
          rel="noreferrer noopener"
          target="_blank"
          className="text-(--el-accent-on-surface) underline underline-offset-2"
        >
          docs/cli.md
        </a>{' '}
        in motir-core.
      </p>
    </>
  )
}
