import { localePageMetadata } from '@/lib/localeMetadata'
import type { Metadata } from 'next'
import {
  fetchCliCommands,
  groupCliCommands,
  type CliCommandsDocument,
} from '@/lib/docs'
import { getCopy } from '@/lib/copy'
import { enterLocale, type LocalePageProps } from '@/i18n/locale'
import { renderDocsParts } from '../../_components/DocsDocument'
import { CodeBlock } from '../../_components/DocSchema'

/*
 * The CLI reference (MOTIR-4046, GENERATED by MOTIR-4395) — rendered from
 * motir-core's PUBLISHED command catalogue (`/api/docs/cli-commands.json`),
 * fetched fresh at request time, exactly as `/docs/api` renders the OpenAPI
 * document and `/docs/mcp/tools` renders the tool catalogue.
 *
 * ⚠️ WHAT WAS HERE, AND WHY IT COULD NOT BE FIXED IN THIS REPOSITORY ALONE.
 * The page was five sentences of positioning: no install line, no
 * authentication, no command list, no flags, no examples. Three `<code>`
 * elements and zero `<pre>` blocks. The obvious fix — generate it from the
 * published catalogue — asserted a door that does not exist: `@motir/cli`
 * publishes `exports: { "./package.json": … }` and nothing else, so
 * `COMMAND_CATALOG` sits inside `dist/index.js` reachable by no import.
 * MOTIR-4390 opened the door as a served artifact; this consumes it.
 *
 * ⚠️ NOTHING ABOUT THE COMMAND SET IS WRITTEN DOWN HERE. No command list, no
 * flag reference, no default server. They arrive over the wire and live in this
 * file for the length of one render — the same property `/docs/mcp/tools`
 * keeps, and `tests/docs/cli.test.tsx` asserts it: the production server's URL
 * may not appear in this source as a literal of its own, because the catalogue
 * carries it and a second copy could disagree with the binary a reader
 * installed. (That guard caught this very comment while it was being written,
 * which is the guard earning its place — the URL is not spelled here either.)
 * What IS typed is the four-line first-run procedure, which is prose about the
 * order a reader types things in; the test carries the ceiling and the reason.
 *
 * ⚠️ THE POSITIONING PARAGRAPH STAYS, as the card asks. It is good writing; it
 * simply is not documentation. It introduces the reference rather than standing
 * in for one.
 *
 * ⚠️ NO FALLBACK, DELIBERATELY. A committed command list is stale exactly when
 * it is displayed and invisible to every guard, since a guard runs on the path
 * where the fetch works — which is the defect MOTIR-4180 removed from this
 * repository. Unreachable ⇒ the page SAYS SO, and the introduction and the
 * hand-offs still render, so a reader is never stranded.
 *
 * ⚠️ MERGE ORDER. `/api/docs/cli-commands.json` ships in MOTIR-4390 and does
 * not exist on the deployed app until that merges and deploys. Until then this
 * page renders the unreachable state, which is the honest answer and not a
 * regression: the alternative is a committed list, which is the thing being
 * removed. motir-core merges first.
 *
 * ── ⚠️ *Where Motir keeps things* IS BACK (MOTIR-4429) ──────────────────────
 * The deleted page carried a `files` section naming the credential store and
 * the project link with the path of each; the restore dropped it, and
 * MOTIR-4397's parity ledger measured that. It is AUTHORED prose, deliberately:
 * the published catalogue carries commands, flags and the default server, and
 * no file path at all — so there is nothing to derive it from, and `lib/docs.ts`'s
 * own carve-out is what allows it. Read from `motir-core`
 * `packages/cli/src/help.ts`'s FILES topic on `origin/main`, which is the same
 * text `motir help files` prints.
 *
 * ⚠️ AND THE CARD SAID *THREE* WHERE THE DELETED PAGE NAMED *TWO* — the card is
 * right and its history is not. The deleted `files` section listed the
 * credential store and the project link; the session exclude list is a THIRD
 * file the CLI grew afterwards, and `motir help files` names all three today.
 * So this restores the shipped set rather than the deleted one, which is the
 * only version that is true. Recorded because a later reader diffing this
 * against `95a2d4468^` will find one row that was never there.
 */
export const dynamic = 'force-dynamic'

export function generateMetadata({
  params,
}: LocalePageProps): Promise<Metadata> {
  return localePageMetadata(params, '/docs/cli', (copy) => ({
    title: copy.docs.metaTitleCli,
    description: copy.docs.metaDescriptionCli,
  }))
}

/** motir-core's own CLI reference — the authority beyond this page. */
const CLI_REFERENCE_URL =
  'https://github.com/moooon-B-V/motir-core/blob/main/docs/cli.md'

/*
 * THE PROSE LIVES IN `content/docs/cli/<locale>.md` (MOTIR-8035). This file keeps
 * what a reader copies (the three code panes), what is generated (the command
 * groups) and the values the prose must not restate (everything the catalogue
 * carries). The document's parts: `body` is the introduction, `meta` the
 * package line, `reference` every section from Install to the end, and
 * `unreachable` the paragraph that renders only when the fetch fails.
 */
const SLOT_NAMES = ['install', 'authenticate', 'link-and-check', 'commands']
const VALUE_NAMES = [
  'packageName',
  'packageVersion',
  'commandCount',
  'nodeRequirement',
  'defaultServer',
]

function Command({
  command,
}: {
  command: CliCommandsDocument['commands'][number]
}) {
  return (
    <li className="py-4">
      <code className="font-(family-name:--font-mono) text-[13.5px] font-semibold text-(--el-text)">
        {command.invocation}
      </code>
      <p className="mt-1 max-w-[68ch] text-[13px] leading-relaxed text-(--el-text-secondary)">
        {command.description}
      </p>
      {command.options.length > 0 ? (
        <dl className="mt-2 grid grid-cols-[minmax(0,14rem)_1fr] gap-x-4 gap-y-1.5">
          {command.options.map((option) => (
            <div key={option.flags} className="contents">
              <dt className="font-(family-name:--font-mono) text-[12.5px] text-(--el-text)">
                {option.flags}
              </dt>
              <dd className="m-0 min-w-0 text-[12.5px] leading-relaxed text-(--el-text-secondary)">
                {option.description}
              </dd>
            </div>
          ))}
        </dl>
      ) : null}
    </li>
  )
}

export default async function CliPage({ params }: LocalePageProps) {
  const locale = await enterLocale(params)
  const copy = await getCopy(locale)
  const labels = {
    sandboxPage: copy.docs.sandbox,
    mcpPage: copy.docs.mcp,
    apiPage: copy.docs.api,
    cliReferenceUrl: CLI_REFERENCE_URL,
  }
  const heading = (
    <h1 className="font-(family-name:--font-serif) text-[30px] leading-[1.2] font-bold tracking-[-0.01em] text-(--el-text)">
      {copy.docs.cli}
    </h1>
  )

  let catalogue: CliCommandsDocument
  try {
    catalogue = await fetchCliCommands()
  } catch {
    // Nothing the catalogue carries exists here: the document still resolves
    // whole (so a stale translation falls back as one), with those slots empty.
    const { parts, note } = await renderDocsParts({
      slug: 'cli',
      locale,
      slots: Object.fromEntries(SLOT_NAMES.map((name) => [name, null])),
      values: {
        ...Object.fromEntries(VALUE_NAMES.map((name) => [name, null])),
        ...labels,
      },
    })
    return (
      <>
        {heading}
        {note}
        {parts.body}
        {parts.unreachable}
      </>
    )
  }

  const groups = groupCliCommands(catalogue)
  const { parts, note } = await renderDocsParts({
    slug: 'cli',
    locale,
    slots: {
      install: (
        <div className="mt-3">
          <CodeBlock
            caption="install"
            code={`${catalogue.installCommand}\n\n# or, without installing:\nnpx ${catalogue.packageName} --help`}
          />
        </div>
      ),
      authenticate: (
        <div className="mt-3">
          <CodeBlock
            caption="authenticate"
            code={`motir login\n\n# or with a token you already hold:\nmotir auth login --server ${catalogue.defaultServer} --token <pat>\n\n# or from the environment:\nexport MOTIR_SERVER=${catalogue.defaultServer}\nexport MOTIR_TOKEN=<pat>`}
          />
        </div>
      ),
      'link-and-check': (
        <div className="mt-3">
          <CodeBlock
            caption="link and check"
            code={`motir link --project ACME\nmotir doctor`}
          />
        </div>
      ),
      commands: groups.map((group) => (
        <section key={group.heading} className="mt-7">
          <h3 className="text-[11px] font-semibold tracking-wide text-(--el-text-secondary) uppercase">
            {group.heading}
          </h3>
          <ul className="mt-2 flex flex-col divide-y divide-(--el-border) border-y border-(--el-border)">
            {group.commands.map((command) => (
              <Command key={command.path} command={command} />
            ))}
          </ul>
        </section>
      )),
    },
    values: {
      // Nodes, not strings: a catalogue value is never parsed as Markdown.
      packageName: <>{catalogue.packageName}</>,
      packageVersion: <>{catalogue.packageVersion}</>,
      commandCount: <>{catalogue.commandCount}</>,
      nodeRequirement: <>{catalogue.nodeRequirement}</>,
      defaultServer: (
        <code className="rounded-(--radius-kbd) bg-(--el-muted) px-1.5 py-0.5 font-(family-name:--font-mono) text-[13px]">
          {catalogue.defaultServer}
        </code>
      ),
      ...labels,
    },
  })

  return (
    <>
      {heading}
      {note}
      {parts.meta}
      {parts.body}
      {parts.reference}
    </>
  )
}
